# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraBottle2Robot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Header_pb2 as Header__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import Camera2Robot_pb2 as Camera2Robot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43\x61meraBottle2Robot.proto\x12\x07mpb_com\x1a\x0cHeader.proto\x1a\x19google/protobuf/any.proto\x1a\x12\x43\x61mera2Robot.proto\"/\n\x0b\x42ottle_info\x12 \n\x04pose\x18\x01 \x03(\x0b\x32\x12.mpb_com.Rgbd_Pose\"l\n\tRgbd_Pose\x12\n\n\x02x1\x18\x01 \x01(\x01\x12\n\n\x02y1\x18\x02 \x01(\x01\x12\n\n\x02z1\x18\x03 \x01(\x01\x12\n\n\x02x2\x18\x04 \x01(\x01\x12\n\n\x02y2\x18\x05 \x01(\x01\x12\n\n\x02z2\x18\x06 \x01(\x01\x12\x0b\n\x03seq\x18\x07 \x01(\r\x12\n\n\x02ts\x18\x08 \x01(\x01\"C\n\x11\x46indBottleRequest\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.mpb_com.Header\x12\r\n\x05times\x18\x02 \x01(\x05\"W\n\x0f\x46indBottleReply\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.mpb_com.Header\x12#\n\x05poses\x18\x02 \x01(\x0b\x32\x14.mpb_com.Bottle_info\"~\n\x19\x43\x61meraBottle2RobotRequest\x12#\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x14.mpb_com.CameraEvent\x12#\n\x05param\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\n\n\x02ts\x18\x03 \x01(\x01\x12\x0b\n\x03seq\x18\x04 \x01(\x01\"x\n\x17\x43\x61meraBottle2RobotReply\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.mpb_com.ErrorMsg\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\n\n\x02ts\x18\x03 \x01(\x01\x12\x0b\n\x03seq\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CameraBottle2Robot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTTLE_INFO._serialized_start=98
  _BOTTLE_INFO._serialized_end=145
  _RGBD_POSE._serialized_start=147
  _RGBD_POSE._serialized_end=255
  _FINDBOTTLEREQUEST._serialized_start=257
  _FINDBOTTLEREQUEST._serialized_end=324
  _FINDBOTTLEREPLY._serialized_start=326
  _FINDBOTTLEREPLY._serialized_end=413
  _CAMERABOTTLE2ROBOTREQUEST._serialized_start=415
  _CAMERABOTTLE2ROBOTREQUEST._serialized_end=541
  _CAMERABOTTLE2ROBOTREPLY._serialized_start=543
  _CAMERABOTTLE2ROBOTREPLY._serialized_end=663
# @@protoc_insertion_point(module_scope)
