# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Camera2Robot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Header_pb2 as Header__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43\x61mera2Robot.proto\x12\x07mpb_com\x1a\x0cHeader.proto\x1a\x19google/protobuf/any.proto\"A\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"H\n\x16\x46indBasestationRequest\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.mpb_com.Header\x12\r\n\x05times\x18\x02 \x01(\x05\"\\\n\x14\x46indBasestationReply\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.mpb_com.Header\x12#\n\x08position\x18\x02 \x01(\x0b\x32\x11.mpb_com.Position\"+\n\x08\x45rrorMsg\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t\"_\n\x13\x43\x61mera2RobotRequest\x12#\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x14.mpb_com.CameraEvent\x12#\n\x05param\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"Y\n\x11\x43\x61mera2RobotReply\x12 \n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.mpb_com.ErrorMsg\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any*2\n\x0b\x43\x61meraEvent\x12\x14\n\x10\x46IND_BASESTATION\x10\x00\x12\r\n\tEVENT_MAX\x10\x63\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Camera2Robot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAEVENT._serialized_start=540
  _CAMERAEVENT._serialized_end=590
  _POSITION._serialized_start=72
  _POSITION._serialized_end=137
  _FINDBASESTATIONREQUEST._serialized_start=139
  _FINDBASESTATIONREQUEST._serialized_end=211
  _FINDBASESTATIONREPLY._serialized_start=213
  _FINDBASESTATIONREPLY._serialized_end=305
  _ERRORMSG._serialized_start=307
  _ERRORMSG._serialized_end=350
  _CAMERA2ROBOTREQUEST._serialized_start=352
  _CAMERA2ROBOTREQUEST._serialized_end=447
  _CAMERA2ROBOTREPLY._serialized_start=449
  _CAMERA2ROBOTREPLY._serialized_end=538
# @@protoc_insertion_point(module_scope)
