# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DualArmCamera.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x44ualArmCamera.proto\x12\x0bmpb_arm_com\"s\n\x0b\x42ottlePoses\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12*\n\tleft_pose\x18\x02 \x01(\x0b\x32\x17.mpb_arm_com.BottlePose\x12+\n\nright_pose\x18\x03 \x01(\x0b\x32\x17.mpb_arm_com.BottlePose\"x\n\nBottlePose\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0c\n\x04roll\x18\x05 \x01(\x01\x12\r\n\x05pitch\x18\x06 \x01(\x01\x12\x0b\n\x03yaw\x18\x07 \x01(\x01\x12\x12\n\ndata_valid\x18\x08 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DualArmCamera_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTTLEPOSES._serialized_start=36
  _BOTTLEPOSES._serialized_end=151
  _BOTTLEPOSE._serialized_start=153
  _BOTTLEPOSE._serialized_end=273
# @@protoc_insertion_point(module_scope)
